##
# This values yaml file provide override values to deploy ppc64le redis service using bitnami redis helm chart 
# for HCL Commerce
#   - chart version: 11.3.4
#   - redis app version: 6.2.3
# 
# To Deploy ppc64le redis using this sample values
# 1. Create a namespace
#    kubectl create ns redis
# 2. Add helm repo
#    helm repo add bitnami https://charts.bitnami.com/bitnami
# 3. Deploy Redis using this override values
#    helm install my-redis bitnami/redis -n redis -f redis-values.yaml --version "11.3.4"
# 4. Monitor deployment until all pods are healthy
# 
# To get the complete values.yaml file, please visit 
#   https://github.com/bitnami/charts/blob/2ed85a611eeb91f6f1495c535f7869f69584f405/bitnami/redis/values.yaml
#
# To get more information related to this version of redis helm chart, please visit
#   https://github.com/bitnami/charts/tree/2ed85a611eeb91f6f1495c535f7869f69584f405/bitnami/redis/README.md
##
fullnameOverride: "hcl-commerce-redis"
replicaCount: 1
usePassword: false
serviceAccount:
  create: false
  name: "default"
image:
  registry: ppc64le
  repository: redis
  tag: 6.2.3
  pullPolicy: IfNotPresent
cluster:
  enabled: false
master:
  command: "/usr/local/bin/docker-entrypoint.sh"
  disableCommands: []
  persistence:
    enabled: false
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 2Gi
  configuration: |-
    appendonly no
    save ""
    maxmemory 1000mb
    maxmemory-policy volatile-lru