##
# This values yaml file provide override values to deploy bitnami redis helm chart 
# for HCL Commerce
#   - chart version: 16.12.0
#   - redis app version: 6.2.7
# 
# To Deploy redis using this sample values
# 1. Create a namespace
#    kubectl create ns redis
# 2. Add helm repo
#    helm repo add bitnami https://charts.bitnami.com/bitnami
# 3. Deploy Redis using this override values
#    helm install my-redis bitnami/redis -n redis -f redis-values.yaml --version "16.12.0"
# 4. Monitor deployment until all pods are healthy
# 
# To get the complete values.yaml file, please visit 
#   https://github.com/bitnami/charts/blob/a1aa868e3e1f5607a56b1f895f0c39548c4d8873/bitnami/redis/values.yaml
#
# To get more information related to this version of redis helm chart, please visit
#   https://github.com/bitnami/charts/blob/a1aa868e3e1f5607a56b1f895f0c39548c4d8873/bitnami/redis/README.md
##
architecture: standalone
fullnameOverride: "hcl-commerce-redis"
replica:
  replicaCount: 0
image:
  registry: docker.io
  repository: bitnami/redis
  tag: 6.2.7-debian-10-r23
  pullPolicy: IfNotPresent
auth:
  enabled: false
master:
  disableCommands: []
  persistence:
    enabled: false
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 2Gi
  configuration: |-
    appendonly no
    save ""
    maxmemory 1000mb
    maxmemory-policy volatile-lru