##
# This values yaml file provide override values to deploy bitnami zookeeper helm chart 
# for HCL Commerce
#   - chart version: 6.7.2
#   - zookeeper app version: 3.7.0
# 
# To Deploy zookeeper using this sample values
# 1. Create a namespace
#    kubectl create ns zookeeper
# 2. Add helm repo
#    helm repo add bitnami https://charts.bitnami.com/bitnami
# 3. Deploy zookeeper using this override values
#    helm install my-zookeeper bitnami/zookeeper -n zookeeper -f zookeeper-values.yaml --version "6.7.2"
# 4. Monitor deployment until all pods are healthy
# 
# To get the complete values.yaml file, please visit 
#   https://github.com/bitnami/charts/blob/1290a275c762676555465b9e31d8ecdf70b38e39/bitnami/zookeeper/values.yaml
#
# To get more information related to this version of zookeeper helm chart, please visit
#   https://github.com/bitnami/charts/blob/ab0dbe4163efec91ebf2cfa48efd77154ff2cdb5/bitnami/zookeeper/README.md
##
image:
  registry: docker.io
  repository: bitnami/zookeeper
  tag: 3.7.0-debian-10-r27
fullnameOverride: "hcl-commerce-zookeeper"
replicaCount: 1
maxClientCnxns: 120
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1024Mi