{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- if and (has "share" $envTypeList) (eq .Values.common.searchEngine "elastic") }}
######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 1996, 2020
######################################################
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.tenant }}{{ .Values.common.environmentName }}{{.Values.queryApp.name}}
  labels:
    app: HCL-Commerce
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "-" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.common.tenant }}{{ .Values.common.environmentName }}{{.Values.queryApp.name}}
    group: {{ .Values.common.tenant }}{{ .Values.common.environmentName }}
    app.kubernetes.io/name: {{ include "name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cloud.google.com/app-protocols: '{"https-port30901":"HTTPS","http-port30900":"HTTP"}'
spec:
  type: NodePort
  ports:
  - port: 30900
    name: http-port30900
  - port: 30901
    name: https-port30901
  {{- if .Values.metrics.enabled }}
  - port: 30280
    name: http-metrics
  {{- end }}
  selector:
    component: {{ .Values.common.tenant }}{{ .Values.common.environmentName }}{{.Values.queryApp.name}}
{{- end -}}