{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- if and (has "share" $envTypeList) (.Values.mustgatherApp.enabled) (eq .Values.common.searchEngine "elastic") }}
######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 1996, 2020
######################################################
## Note: Must-Gather application is NOT production-ready
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.tenant }}{{ .Values.common.environmentName }}{{.Values.mustgatherApp.name}}
  labels:
    app: HCL-Commerce
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "-" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.common.tenant }}{{ .Values.common.environmentName }}{{.Values.mustgatherApp.name}}
    group: {{ .Values.common.tenant }}{{ .Values.common.environmentName }}
    app.kubernetes.io/name: {{ include "name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cloud.google.com/app-protocols: '{"https-port42021":"HTTPS"}'
spec:
  type: NodePort
  ports:
  - port: 42021
    name: https-port42021
  selector:
    component: {{ .Values.common.tenant }}{{ .Values.common.environmentName }}{{.Values.mustgatherApp.name}}
{{- end -}}