{{- if $.Values.xcApp.enabled }}
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) }}
{{- range $envType := $envTypeList }}
{{- if ne $envType "share" }}
######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 1996, 2020
######################################################
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}{{$.Values.xcApp.name}}
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    component: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}{{$.Values.xcApp.name}}
    app.kubernetes.io/name: {{ include "name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    cloud.google.com/app-protocols: '{"https-port9443":"HTTPS","http-port9080":"HTTP"}'
spec:
  ports:
  - port: 9080
    name: http-port9080
  - port: 9443
    name: https-port9443
  {{- if $.Values.metrics.enabled }}
  - port: 9280
    name: http-metrics
  {{- end }}
  selector:
    component: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}{{$.Values.xcApp.name}}
{{- end }}
---
{{- end }}
{{- end }}